name: buildflow_mobile
description: FOVAME BuildFlow mobile reference client
publish_to: none
version: 0.1.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  mobile_scanner: ^5.2.3
  flutter_secure_storage: ^9.2.2
